### PR TITLE
Feature/structured configs

### PR DESCRIPTION
**Pull request by ANaka**
Taking a pass at #65 - validating arguments via a structured configuration schema

- Adds an attrs dataclass `pytti.config.structured_config.ConfigSchema` with some basic validation e.g. `animation_mode` must be in `['off', '2D', '3D', 'Video Source']`
- Adds some basic tests that validation works

I think there would still be a fair bit of work here to get this working well in the larger library. The `OmegaConf.to_container` call in `workhorse.py` would maybe need to be switched to `OmegaConf.to_object` to invoke the validator methods in the dataclass. Might also make sense to be declaring the schema in a more hierarchical way, which would take some noodling

### CODE REVIEW

**Comment by ANaka** [comment]
Accidentally got caught with merging some stuff from main, not totally sure what happened there

**Comment by dmarx** [comment]
This is great, thanks so much for contributing! It looks like you're getting defaults from the values in the colab notebook demo (which I've been meaning to change): before I merge, could you update to use the less opinionated defaults that currently reside here? https://github.com/pytti-tools/pytti-core/blob/main/src/pytti/assets/default.yaml

If we can merge with that already in place, I can update the `pytti.warmup` script to build missing default configs from the structured configs directly. 

Regarding your other feedback:

Honestly, I'm only even invoking `OmegaConf.to_container` at all because I was injecting a config object into a location that was expecting a dict. Really, most of that stuff should go completely to be more idiomatic for hydra. Ditto the hierarchical schema: I completely agree that this would be better. I'm really just using the flat schema because that's basically what was already there. The work you've put in with the structured configs will make it a lot easier to migrate to a proper hierarchy I think, which should also make it easier to constrain the users view to settings that are relevant to options they're considering (e.g. not making the user feel like they need to provide 2D animation options when they're using the 3D animation mode, etc).

Thanks again! (and double thanks for writing tests!)

**Comment by ANaka** [comment]
>could you update to use the less opinionated defaults that currently reside here? https://github.com/pytti-tools/pytti-core/blob/main/src/pytti/assets/default.yaml
Should be updated now!

>Honestly, I'm only even invoking OmegaConf.to_container at all because I was injecting a config object into a location that was expecting a dict. Really, most of that stuff should go completely to be more idiomatic for hydra.
Makes sense - I mainly bring it up because I was nervous about proposing a change there myself while I'm still getting a feel for the overall library.

**Comment by dmarx** [comment]
yeah hydra is funny. honestly, I think it added more headaches than it solved and I'm increasingly thinking of just backing hydra out. 

I saw you added tests, did you run the existing ones? I'm getting 31 failed 15 passed. Looks like basically the whole TestE2e suite is failling with the same error: `TypeError: __init__() got multiple values for argument 'params'`

**Comment by dmarx** [comment]
I think I see what happened, looks like you built your changes on top of an older version of the repo, which unfortunately didn't catch a big refactor. I see you merged the changes from main, but I think that didn't work propertly for some reason and ended up overriding some changes from the refactor, in particular (I think) changes to DirectImageGuide, which significantly expanded its call signature. That expanded call signature is frankly a problem in itself, but in any event... I'll take a stab at fixing this tomorrow if you don't beat me to it. I think instead of merging main in, we should try to rebase your changes on top of main. We'll figure it out. 

Thanks again for your contributions and patience.

**Comment by dmarx** [comment]
figured it out, basically my bad cause I've just gotten so used to being the only contributor. You stacked your work on top of the dev branch, which should have made sense. what you didn't realize was that I had actually already merged that branch with a squashed commit and should have deleted it afterwards to avoid precisely what just happened here. 

I've rebased and cleaned stuff up locally, all tests passed except 3 which are supposed to fail because they're documenting an unresolved bug. going to close this PR and open a new one with the repaired branch for provenance.

**Comment by ANaka** [comment]
> You stacked your work on top of the dev branch, which should have made sense. what you didn't realize was that I had actually already merged that branch with a squashed commit

oof, sorry I missed that - didn't mean to make extra work for you. Thanks for cleaning it up!

**Comment by ANaka** [comment]
>yeah hydra is funny. honestly, I think it added more headaches than it solved and I'm increasingly thinking of just backing hydra out.

I'm working pretty heavily with hydra on another project and I can relate. It can make simple things pretty complex sometimes and its docs are okay but not great - they leave a lot to the user when it comes to scaling it out to a complex use case. 

That being said - one of the things that I really like about pytti is that it takes the problem of configuration seriously. Whereas it feels like it's often an afterthought in much of the other text-to-image work out there, perhaps because a lot of the community is very colab-centric. I've been wanting to explore the outputs of these models more systematically for a while now, and it feels like having some kind of framework (whether that's hydra or something else) for defining large families of configuration is really important for doing that.

**Pull request closed without merging**
